# THIS FILE OVERWRITES THE DEFAULT /etc/http/conf/httpd.conf FILE FOR APACHE 2.4.
# WE DO A NUMBER OF THINGS DIFFERENTLY (PRIMARILY HAVING TO DO WITH ENV VARS) THAN
# THE DEFAULT, WHICH IS WHY WE OVERWRITE THIS FILE.
# THIS FILE HAS BEEN SIMPLIFIED DOWN TO ITS BAREST ESSENSE.

ServerRoot "/etc/httpd"

# Include module configs first.
# CNK 8/1/18 we could save some memory if we pruned base.conf a bit but we did exclude
# lua, dav, and cgi by loading only the files named below rather than *.conf.
Include conf.modules.d/00-base.conf
Include conf.modules.d/00-mpm.conf
Include conf.modules.d/00-proxy.conf
Include conf.modules.d/00-ssl.conf
Include conf.modules.d/00-systemd.conf

# Basic Apache configs.
User apache
Group apache
AddDefaultCharset UTF-8
EnableSendfile on
<Directory />
    # Denies access to the entirety of our server's filesystem. We then explicitly
    # permit access to web content directories in apache.conf.
    AllowOverride none
    Require all denied
</Directory>
<IfModule mime_module>
    TypesConfig /etc/mime.types
    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
</IfModule>
<IfModule mime_magic_module>
    MIMEMagicFile conf/magic
</IfModule>

# Now include our specific configs so they can override values as needed.
Include conf.d/ssl.conf
Include conf.d/seedling.conf
