# LIKE WE DO WITH httpd.conf, WE COMPLETELY REPLACE THE DEFAULT /etc/httpd/conf.d/ssl.conf
# FILE WITH OUR OWN COPY. THIS LETS US PREVENT IT FROM DOING THINGS WE NEED TO DO OURSELVES.
# THIS FILE HAS BEEN SIMPLIFIED DOWN TO ITS BAREST ESSENSE.

SSLPassPhraseDialog exec:/usr/libexec/httpd-ssl-pass-dialog
SSLSessionCache         shmcb:/run/httpd/sslcache(512000)
SSLSessionCacheTimeout  300
SSLRandomSeed startup file:/dev/urandom  256
SSLRandomSeed connect builtin
SSLCryptoDevice builtin
