---
version: "3.8"

services:

  seedling:
    image: seedling:latest
    container_name: seedling
    restart: always
    hostname: seedling
    ports:
      - "8443:8443"
    env_file:
      - .env
    depends_on:
      - mysql
    command: bin/wait-for-it.sh mysql:3306 --and /usr/local/bin/supervisord

  mysql:
    image: mysql:8.0.23
    container_name: db-seedling
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    cap_add:
      # removes error messages like: mbind: Operation not permitted
      - SYS_NICE
    ports:
      # Expose port 3306 on the container as port 3307 on the host, so that sql
      # clients can connect to it.
      - "3307:3306"
    volumes:
      - ./sql/docker/my.cnf:/etc/mysql/conf.d/dev.cnf
      - ./sql/docker:/docker-entrypoint-initdb.d
      # Mount the sql server's filesystem into a Docker Volume, so it persists
      # across invocations of the container.  To delete the database and start
      # over, run: docker volume rm seedling_seedling_data
      - seedling_data:/var/lib/mysql

  mail:
    image: mailhog/mailhog
    container_name: mail
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  # The Docker volume in which the database's files are stored. Works in tandem
  # with the "mysql8_data:/var/lib/mysql" volume mount defined above.
  seedling_data:
