version: '2'

services:
  seedling:
    tty: true
    env_file:
      # Your test environment definition file must exist at this location on your development machine.
      - "/etc/context.d/seedling_test.env"
    command:
      bin/wait-for-it.sh -t 30 elastic:9200 --and ./manage.py test -v3 --keepdb
