# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

# MAINTENANCE NOTE: This part of the custom_auth.User migration MUST be separate from 0001_initial.
# If it's not, there will be a circular dependency, because wagtailcore references AUTH_USER_MODEL, and this Site
# reference in SiteSpecificDelegation depends on wagtailcore. This is why 0001_initial has only a dependency on 'auth'.


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitespecificdelegation',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Site'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sitespecificdelegation',
            unique_together=set([('delegator', 'delegate', 'site')]),
        ),
    ]
