# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-11 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_add_site_DO_NOT_DELETE__SEE_COMMENTS_INSIDE'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitespecificdelegation',
            name='delegate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegates_delegation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitespecificdelegation',
            name='delegator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_for_delegation', to=settings.AUTH_USER_MODEL),
        ),
    ]
