# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_update_SiteSpecificDelegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='Enable this flag to make this user a Super Admin, which causes the system to treat them like they are an Admin on whatever site they are logged into.', verbose_name='Super Admin'),
        ),
    ]
