[supervisord]
nodaemon=true
logfile=/dev/fd/1
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:gunicorn]
command=gunicorn --log-config etc/gunicorn_logging.conf --config python:config.gunicorn_config config.wsgi:application
user=gunicorn
directory=/seedling
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:apache]
command=/bin/bash -c "exec /usr/sbin/httpd -DFOREGROUND"
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
killasgroup=true
stopasgroup=true
